### ISSUE TITLE
09.MNIST 의 MNIST(logistic reg.).py 에 오타가 있는 것 같습니다.

### ISSUE THREAD

**Issue by brainstormot** [gicheonkang/TF-Tutorial#1]
35번째 줄인  avg_cost += session.run(cost, feed_dict={X: batch_xs, Y: batch_ys}) / total_batch 가 들여쓰기가 되어야 하는 것 같습니다.

**Comment by gicheonkang** [comment]
아 들여쓰기가 안되어 있었네요 피드백 감사합니다.
